name: Build, Package, and Upload C Programs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: Build Windows Binaries, Package, and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install mingw and zip
        run: sudo apt-get update && sudo apt-get install -y mingw-w64 zip

      - name: Create Windows build directory
        run: mkdir -p build/windows

      - name: Compile all .c files for Windows
        run: |
          # Loop through all .c files and compile each one for Windows
          for src in $(find . -type f -name "*.c"); do
              exe=$(echo "$src" | sed 's#^\./##; s#[/\\]#_#g; s/\.c$//').exe
              echo "Compiling $src to build/windows/${exe}"
              x86_64-w64-mingw32-gcc "$src" -o "build/windows/${exe}" || { echo "Compilation failed for $src"; exit 1; }
          done

      - name: Create windows.zip archive
        run: |
          cd build/windows
          zip -r ../../windows.zip *

      - name: Upload Windows Archive
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows-archive
          path: windows.zip
